name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  OAUTH_DIR: oauth_new

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.OAUTH_DIR }}/package-lock.json

      - name: Install dependencies
        run: |
          cd ${{ env.OAUTH_DIR }}
          npm ci

      - name: Build OAuth app
        run: |
          cd ${{ env.OAUTH_DIR }}
          NODE_ENV=production npm run build
        env:
          VITE_ADMIN: ${{ secrets.VITE_ADMIN }}
          VITE_PDS: ${{ secrets.VITE_PDS }}
          VITE_HANDLE_LIST: ${{ secrets.VITE_HANDLE_LIST }}
          VITE_COLLECTION: ${{ secrets.VITE_COLLECTION }}
          VITE_OAUTH_CLIENT_ID: ${{ secrets.VITE_OAUTH_CLIENT_ID }}
          VITE_OAUTH_REDIRECT_URI: ${{ secrets.VITE_OAUTH_REDIRECT_URI }}
          VITE_ENABLE_TEST_UI: 'false'
          VITE_ENABLE_DEBUG: 'false'

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: ${{ env.OAUTH_DIR }}/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          deploymentName: Production