name = "ollama-proxy"
main = "ollama-proxy.js"
compatibility_date = "2024-01-01"

# 環境変数
[vars]
REQUIRE_AUTH = false

# 本番環境
[env.production.vars]
OLLAMA_API_URL = "https://ollama.syui.ai/api/generate"
REQUIRE_AUTH = true

# KVネームスペース（レート制限用）
[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "your-kv-namespace-id"

# シークレット（wrangler secret putで設定）
# OLLAMA_INTERNAL_TOKEN = "your-internal-token"